spring:
  application:
    name: uniflow
  profiles:
    active: "test"
  jpa:
    open-in-view: false
  security:
    jwt:
      token:
        secret-key: 53cr37
        expire-length: 3600000
server:
  port: 8080