spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_uniflow
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    #properties:
      #hibernate:
        #format_sql: true

logging:
  level:
    root: INFO
    #root: TRACE
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE

