spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_uniflow
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create